### ISSUE TITLE
seqSlidingWindow exported?

### ISSUE THREAD

**Issue by sa-lee** [zhengxwen/SeqArray#15]
Just wondering what happened to seqSlidingWindow method?

Is there any plans to put it back in the future?

**Comment by zhengxwen** [comment]
`seqSlidingWindow()` is not one of the key functions in SeqArray. It might be back after BioC3.3 is released in April.

**Comment by sa-lee** [comment]
Cheers thanks!

**Comment by zhengxwen** [comment]
The new functions `seqUnitSlidingWindows()` and `seqUnitApply()` in SeqArray_1.27.1 bring sliding windows back.
