### ISSUE TITLE
"push+intersect" does not behave as expected

### ISSUE THREAD

**Issue by smgogarten** [zhengxwen/SeqArray#20]
Using `seqSetFilter` with `action="push+intersect"` does not apply the intersection with the previous filter.
`"intersect"` alone has the correct behavior:
```
> seqSetFilter(gds, variant.id=1:100)
# of selected variants: 100
> seqSetFilter(gds, variant.id=51:110, action="intersect")
# of selected variants: 50
```
But `"push+intersect"` does not:
```
> seqSetFilter(gds, variant.id=1:100)
# of selected variants: 100
> seqSetFilter(gds, variant.id=51:110, action="push+intersect")
# of selected variants: 60
```

**Comment by smgogarten** [comment]
Given that `action="pop"` works even when the last filter was not a `"push"`, what is the intended use of `"push"` and `"push_intersect"`?
```
> seqSetFilter(gds, variant.id=1:100)
# of selected variants: 100
>  seqSetFilter(gds, variant.id=51:110, action="intersect")
# of selected variants: 50
> seqSetFilter(gds, action="pop")
> sum(seqGetFilter(gds)$variant.sel)
[1] 100
```

**Comment by zhengxwen** [comment]
I will check seqSetFilter().

The `action="pop"` and `action="push"` in `seqSetFilter()` allow that users temporarily store the filters without copying the filters to a new variable. E.g. define a function with variant.id input:

```
your_function <- function(gds, sel.variant)
{
    seqSetFilter(gds, variant.id=sel.variant, action="push+set")
    on.exit({ seqSetFilter(gds, action="pop") })

    # your codes
    ...
}
```

**Comment by zhengxwen** [comment]
fix it with the last github commit.
