### ISSUE TITLE
seqGDS2VCF does not generate a bgzip vcf file

### ISSUE THREAD

**Issue by trb8** [zhengxwen/SeqArray#28]
seqGDS2VCF(gds, "output.vcf.gz") generates a gzipped vcf but not bgzip-ed vcf. So tabix indexing fails.

**Comment by zhengxwen** [comment]
I have resolved this problem in the latest version.
See: http://bioconductor.org/packages/devel/bioc/news/SeqArray/NEWS
Please install the latest version from GitHup.
