### ISSUE TITLE
VCF2GDS error with phased VCF files

### ISSUE THREAD

**Issue by dtaliun** [zhengxwen/SeqArray#34]
Message:

Error in seqVCF2GDS(vcffile, gdsfile.tmp, fmt.import = fmt.import, storage.option = "LZMA_RA",  : 
  Invalid integer conversion '1|1'

SessionInfo:
R version 3.5.1 (2018-07-02)
Platform: x86_64-pc-linux-gnu (64-bit)
Running under: Ubuntu 16.04.5 LTS
 SeqArray_1.21.4 
gdsfmt_1.17.4

**Comment by zhengxwen** [comment]
It is the issue as #32.
I am tracking the changes from R_3.4.3 to R_3.5.1, and I am afraid it is not easy to fix this issue.
Please use R_3.4.3 for an immediate solution.

**Comment by dtaliun** [comment]
Thanks, R_3.4.4 works also

**Comment by zhengxwen** [comment]
Could you please test this commit https://github.com/zhengxwen/SeqArray/commit/67b4c314deb05b6888416b9a7ae718f870df5cba to see weather it is fixed?

```
library("devtools")
install_github("zhengxwen/SeqArray")
```
