### ISSUE TITLE
get genotypes with nucleotides ?

### ISSUE THREAD

**Issue by thierrygosselin** [zhengxwen/SeqArray#45]
Is there a way to get (`SeqArray::seqGetData`) genotypes in the form of nucleotides, e.g. A/T 
similar to `SeqVarTools::getGenotypeAlleles` ? The last one is very slow for big VCFs.
cheers
Thierry

**Comment by smgogarten** [comment]
I might be able to speed up the implementation in SeqVarTools (no guarantees); I opened an issue here: https://github.com/smgogarten/SeqVarTools/issues/2

If Xiuwen has a better solution, I'd be happy to make use of it.

**Comment by thierrygosselin** [comment]
Awesome!
