### ISSUE TITLE
Changing genotypes

### ISSUE THREAD

**Issue by thierrygosselin** [zhengxwen/SeqArray#51]
The 3D array for “genotype” is presence/absence of REF and ALT alleles coded 0/1, how’s the missing coded?
When I use NA it’s not converted to missing.

I can have a reproducible example if it helps

**Comment by thierrygosselin** [comment]
recoding `NA` to `0x0F` seems to fix my problem...

**Comment by zhengxwen** [comment]
or recoding NA to -1
