### ISSUE TITLE
genotypes have been called in haploid mode, they don't have a phase

### ISSUE THREAD

**Issue by JiruHan** [zhengxwen/SeqArray#52]
Hi there,
I have a problem using the function getGenotype, when I run getGenotype(gds), it has an errot:
Error in seqApply(gdsobj, c(geno = "genotype", phase = "phase"), function(x) { : 
  The GDS node "phase/data" does not exist.
I don't know how to solve this problem, could you please help me?
Thanks in advance!

Cheers,
Jiru

**Comment by smgogarten** [comment]
Try `seqGetData(gds, "genotype")`. Opened as issue in SeqVarTools: https://github.com/smgogarten/SeqVarTools/issues/3

**Comment by smgogarten** [comment]
Fixed in SeqVarTools https://github.com/smgogarten/SeqVarTools/commit/390dfa26d10c22167393a93b4b29e16f86f58dd4
