### ISSUE TITLE
Importing DArT file and converting to VCF

### ISSUE THREAD

**Issue by pezhmansafdari** [zhengxwen/SeqArray#54]
Hi,
 I am trying to import a DArt file and convert it to VCF because I want to calculate nucleotide diversity. When I use the command:

SNP <- radiator::read_dart("Report_DPlan16-2487_SNP_singlerow.csv", strata="dart.strata.tsv")

I get the following error:

Reading DArT file...
Number of blacklisted samples: 0
DArT SNP format: genotypes in 1 Row
Generating genotypes and calibrating REF/ALT alleles...
Number of markers recalibrated based on counts of allele: 8759
Generating GDS...
Error in SeqArray::seqVCF2GDS(vcf.fn = paste0(temp.file, ".vcf"), out.fn = if (length(filename) >  : 
  There is no sample in the VCF file.

Would you please tell me what could be the source of the problem?

All the bests,
Pezhman Safdari

**Comment by zhengxw-ab** [comment]
You might need to update your installed SeqArray package, and the latest SeqArray can import a VCF file with no sample.
