### ISSUE TITLE
Generate GDS from VCF error

### ISSUE THREAD

**Issue by cinaljess** [zhengxwen/SeqArray#6]
Hello & thanks for the great work. This is similar to previous issue by randomStat. I used GATK to analyze whole genome sequencing data for two samples. I used snpEff for annotation and then used GATK's variantannotator to make the final vcf file. I can send part of the VCF file if you offer. When I try to make a GDS file out of it, I get the following error:

The Variant Call Format (VCF) header:
        file format: VCFv4.1
        the number of sets of chromosomes (ploidy): 2
Parsing "10029667.1.fb.annot.vcf.gz" ...
Error:  FILE: 10029667.1.fb.annot.vcf.gz
        LINE: 12599, COLUMN: 8, AC=4;AF=1;AN=4;DB;DP=106;DPB=106;GTI=0;NS=2;NUMALT=1;ODDS=71.5486;PQR=0;PRO=0;QR=0;RO=0;SNPEFF_EFFECT=INTRON;SNPEFF_EXON_ID=6;SNPEFF_FUNCTIONAL_CLASS=NONE;SNPEFF_GENE_BIOTYPE=protein_coding;SNPEFF_GENE_NAME=ACOT7;SNPEFF_IMPACT=MODIFIER;SNPEFF_TRANSCRIPT_ID=ENST00000361521;SNV;SRF=0;SRP=0;SRR=0;TYPE=snp
                FILE: fullpath/10029667.1.fb.annot.vcf.gz
        LINE: 12599, COLUMN: 8, AC=4;AF=1;AN=4;DB;DP=106;DPB=106;GTI=0;NS=2;NUMALT=1;ODDS=71.5486;PQR=0;PRO=0;QR=0;RO=0;SNPEFF_EFFECT=INTRON;SNPEFF_EXON_ID=6;SNPEFF_FUNCTIONAL_CLASS=NONE;SNPEFF_GENE_BIOTYPE=protein_coding;SNPEFF_GENE_NAME=ACOT7;SNPEFF_IMPACT=MODIFIER;SNPEFF_TRANSCRIPT_ID=ENST00000361521;SNV;SRF=0;SRP=0;SRR=0;TYPE=snp

 >R_ReplConsole(): before "for(;;)" {main.c}

This is the only error given by R --verbose.

R version 3.1.1 (2014-07-10)
>installed.packages()
RSQLite           NA                    NA      NA     "yes"            "3.1.1"
rtracklayer       NA                    NA      NA     NA               "3.1.1"
scales            NA                    NA      NA     "no"             "3.1.1"
scatterplot3d     NA                    NA      NA     "no"             "3.1.1"
schoolmath        NA                    NA      NA     NA               "3.1.1"
sendmailR         NA                    NA      NA     "no"             "3.1.1"
SeqArray          NA                    NA      NA     NA               "3.1.1"
SeqVarTools       NA                    NA      NA     NA               "3.1.1"
ShortRead         NA                    NA      NA     NA               "3.1.1"
SparseM           NA                    NA      NA     "yes"            "3.1.1"
stringr           NA                    NA      NA     NA               "3.1.1"
VariantAnnotation NA                    NA      NA     NA               "3.1.1"
XML               NA                    NA      NA     "yes"            "3.1.1"
xtable            NA                    NA      NA     "no"             "3.1.1"
XVector           NA                    NA      NA     NA               "3.1.1"
zlibbioc          NA                    NA      NA     NA               "3.1.1"
base              NA                    NA      NA     NA               "3.1.1"
boot              NA                    NA      NA     "no"             "3.1.1"
class             NA                    NA      NA     "yes"            "3.1.1"
cluster           NA                    NA      NA     "yes"            "3.1.1"
codetools         NA                    NA      NA     "no"             "3.1.1"
compiler          NA                    NA      NA     NA               "3.1.1"
datasets          NA                    NA      NA     NA               "3.1.1"
foreign           NA                    NA      NA     "yes"            "3.1.1"
graphics          NA                    NA      NA     NA               "3.1.1"
grDevices         NA                    NA      NA     NA               "3.1.1"
grid              NA                    NA      NA     NA               "3.1.1"
KernSmooth        NA                    NA      NA     "yes"            "3.1.1"
lattice           NA                    NA      NA     "yes"            "3.1.1"
MASS              NA                    NA      NA     "yes"            "3.1.1"
Matrix            NA                    NA      NA     "yes"            "3.1.1"
methods           NA                    NA      NA     NA               "3.1.1"
mgcv              NA                    NA      NA     "yes"            "3.1.1"
nlme              NA                    NA      NA     "yes"            "3.1.1"
nnet              NA                    NA      NA     "yes"            "3.1.1"
parallel          NA                    NA      NA     NA               "3.1.1"
rpart             NA                    NA      NA     "yes"            "3.1.1"
spatial           NA                    NA      NA     "yes"            "3.1.1"
splines           NA                    NA      NA     NA               "3.1.1"
stats             NA                    NA      NA     NA               "3.1.1"
stats4            NA                    NA      NA     NA               "3.1.1"
survival          NA                    NA      NA     "yes"            "3.1.1"
tcltk             NA                    NA      NA     NA               "3.1.1"
tools             NA                    NA      NA     NA               "3.1.1"
utils             NA                    NA      NA     NA               "3.1.1"

**Comment by zhengxwen** [comment]
Please send me a part of the VCF file.
