### ISSUE TITLE
seqBED2GDS fails if "#" character is present in variant identifier

### ISSUE THREAD

**Issue by smgogarten** [zhengxwen/SeqArray#63]
I have a BIM file where one of the variant identifiers contains a comment character: `HPA#_SNP1`. When trying to process this file, `seqBED2GDS` fails with this error:
```
Error in scan(file = file, what = what, sep = sep, quote = quote, dec = dec,  : 
  line 341656 did not have 6 elements
```
Can you turn off comment character recognition in `seqBED2GDS`, or add an option to do so? Modifying this line:
https://github.com/zhengxwen/SeqArray/blob/master/R/Conversion.R#L831
with `comment.char=""` would fix the issue.

**Comment by zhengxwen** [comment]
the commit [3a58ab0](https://github.com/zhengxwen/SeqArray/commit/3a58ab057a9aa58a90b31386eeb944c9136744d9) fix the problem.
