### ISSUE TITLE
error: 

### ISSUE THREAD

**Issue by 229668880** [zhengxwen/SeqArray#67]
I used seqSNP2GDS  function to convert SNP GDS file into SeqArray GDS file. When I try to do seqGetData(seqvargds, "genotype"), it gives error: Invalid dimension of 'genotype/data' .

seqGetData(seqvar, "allele")[1:20] gives results like:
 [1] "G,A"  "C,T"  "T,TC" "C,A"  "A,G"  "G,GA" "T,G"  "A,G"  "C,A"  "C,T"
[11] "C,T"  "C,CT" "A,C"  "T,A"  "C,A"  "C,T"  "C,T"  "T,C"  "T,C"  "C,T"

How can I find where the problem is? My original SNP GDS file?  This file doesn't have problem, as I used it in association test with GENESIS package. Everything is ok there.

**Comment by zhengxwen** [comment]
If your SNP GDS file stores imputed dosages, please use `seqGetData(server, "annotation/format/DS")` to access the data.

**Comment by 229668880** [comment]
Thanks.
