### ISSUE TITLE
SeqAlleleCount issue with unused argument (.progress = TRUE)

### ISSUE THREAD

**Issue by leoneago** [zhengxwen/SeqArray#83]
Hi @zhengxwen 
After trying to use radiator to filter my RADseq data, I got this error message from SeqArray:

Error in SeqArray::seqAlleleCount(gdsfile = gds, ref.allele = NULL, .progress = TRUE,  : 
  unused argument (.progress = TRUE)

How can I solve this?
Thanks in advance,
AL

**Comment by zhengxwen** [comment]
```
     seqAlleleCount(gdsfile, ref.allele=0L, minor=FALSE, parallel=seqGetParallel(),
         verbose=FALSE)
```
`.progress = TRUE` should be replaced by `verbose=TRUE`.
