### ISSUE TITLE
Is seqAlleleCount exported?

### ISSUE THREAD

**Issue by DavisBrian** [zhengxwen/SeqArray#9]
I'm trying to determine if I have an installation error or if a couple functions (seqAlleleCount and seqNumAllele) aren't exported.

> library(SeqArray")
> out_file <- "AA_ARIC_plus_JHS_v2f_chr6.gds"
> gt_gds = seqOpen(out_file)
> seqSummary(gt_gds)
File: AA_ARIC_plus_JHS_v2f_chr6.gds
Sequence Variant Format: v1.0
The number of samples: 3856
The number of variants: 15467
The chromosomes:
    6  <NA> 
15467     0 
The number of alleles per site:
    2 
15467 
Annotation, information variables:
        NS, 1, Integer, Number of samples with data
        AC, A, Float, Allele Count
Annotation, format variables:
> seqAlleleCount(gt_gds)
Error: could not find function "seqAlleleCount"
> seqNumAllele(gt_gds)
Error: could not find function "seqNumAllele"

**Comment by zhengxwen** [comment]
Please run `sessionInfo()`, show me the version of SeqArray you are using.
Please install the latest version, `seqAlleleCount()` and `seqNumAllele()` are available in Version>=1.9.6.

**Comment by DavisBrian** [comment]
Somehow when I pulled from BioConductor this morning it installed 1.8.0.  After upgrading it worked.

Thanks!
